name: Domain Reviewer

on: [pull_request]

jobs:
  domains-reviewer:
    runs-on: ubuntu-24.04
    steps:
      - uses: ./action.yml
        with:
          configuration-url: https://raw.githubusercontent.com/axel7083/action-domain/refs/heads/main/domains.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
